### PR TITLE
feat: always use latest dprint version

### LINKED ISSUE #2: Always use latest dprint version unless a version is explicitly specified
As title. Need to break away from always needing to always do dprint check releases.

### PR DESCRIPTION
**Pull request by kevgo**
resolves #2

### CODE REVIEW

**Comment by kevgo** [comment]
Duplicate of #4, closing

**Comment by dsherret** [comment]
I'm going to merge #4 into this. This is better 😅

**Comment by kevgo** [comment]
Apologies for the merge conflicts. I let you finalize this branch.

**Comment by dsherret** [comment]
@kevgo oh, no big deal at all! Thanks for the help 😀

I ended up naming it `dprint-version` just because I found "version" alone confusing because it makes me think of the action version instead (also, deno uses `deno-version` so this aligns with that)

**Comment by kevgo** [comment]
> I ended up naming it dprint-version just because I found "version" alone confusing because it makes me think of the action version instead (also, deno uses deno-version so this aligns with that)

Great idea, I like it!

**Pull request merged**
